/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.jeeserver.base.embedded.project.wizard;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import org.netbeans.api.project.Project;
import org.netbeans.spi.project.ui.CustomizerProvider;

/**
 *
 * @author Valery
 */
public class MainClassChooserPanelVisual extends javax.swing.JPanel {
    
    private static final String NO_MAIN_CLASS_FOUND = "No Main Class Found";
    
    private final JButton selectedButton;
    private final JButton cancelButton;
    private Project serverProject;
    /**
     * Creates new form MainClassChooserPanelVisual
     * @param selectedButton
     * @param cancelButton
     */
    public MainClassChooserPanelVisual(JButton selectedButton,JButton cancelButton) {
    //public MainClassChooserPanelVisual() {
        initComponents();
        this.selectedButton = selectedButton;
        this.cancelButton = cancelButton;
        
        
        this.mainClassesList.addListSelectionListener((ListSelectionEvent e) -> {
            if ( mainClassesList.getSelectedIndex() < 0 )  {
                selectedButton.setEnabled(false);
            } else if ( NO_MAIN_CLASS_FOUND.equals(mainClassesList.getSelectedValue())   ) {
                selectedButton.setEnabled(false);
            } else {
                selectedButton.setEnabled(true);
            }
            
        });
        
    }

    public Project getServerProject() {
        return serverProject;
    }

    public void setServerProject(Project serverProject) {
        this.serverProject = serverProject;
    }
    
    public JList getMainClassesList() {
        return this.mainClassesList;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainClassesList = new javax.swing.JList();
        customizeButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Available Main Classes:"); // NOI18N

        mainClassesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        mainClassesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mainClassesList.setToolTipText(org.openide.util.NbBundle.getMessage(MainClassChooserPanelVisual.class, "MainClassChooserPanelVisual.mainClassesList.toolTipText")); // NOI18N
        jScrollPane1.setViewportView(mainClassesList);

        org.openide.awt.Mnemonics.setLocalizedText(customizeButton, "Customize"); // NOI18N
        customizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(67, 221, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(customizeButton)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizeButtonActionPerformed
        CustomizerProvider cp = serverProject.getLookup().lookup(CustomizerProvider.class);
        if ( cp != null ) {
            cp.showCustomizer();
        }

    }//GEN-LAST:event_customizeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customizeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList mainClassesList;
    // End of variables declaration//GEN-END:variables
}
