package org.netbeans.modules.jeeserver.base.embedded.project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.enterprise.deploy.shared.factories.DeploymentFactoryManager;
import javax.enterprise.deploy.spi.factories.DeploymentFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import org.netbeans.modules.jeeserver.base.embedded.specifics.EmbeddedServerSpecifics;
import org.netbeans.modules.jeeserver.base.deployment.specifics.ServerSpecifics;
import org.netbeans.modules.jeeserver.base.deployment.specifics.ServerSpecificsProvider;
import org.netbeans.modules.jeeserver.base.embedded.utils.SuiteConstants;
import org.netbeans.modules.jeeserver.base.embedded.utils.SuiteUtil;
import org.netbeans.modules.jeeserver.base.deployment.utils.BaseUtils;
import org.netbeans.spi.project.ui.support.ProjectChooser;
import org.openide.WizardDescriptor;
import org.openide.WizardValidationException;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle;

public class EmbServerPanelVisual extends JPanel implements DocumentListener, ChangeListener, ActionListener {

    /**
     * Properties used for DocumentListeners
     */
    public static final String PROP_PROJECT_NAME = "projectName";
    public static final String PROP_PORT = "portNumber";
    public static final String PROP_DEBUG_PORT = "debugPortNumber";
    public static final String PROP_SHUTDOWN_PORT = "shutdownPortNumber";
    private final EmbServerWizardPanel panel;
    private WizardDescriptor wiz;

    public EmbServerPanelVisual(EmbServerWizardPanel panel) {
        initComponents();
        this.panel = panel;
        // Register listener on the textFields to make the automatic updates
        addListeners();
    }

    private void addListeners() {
    //    this.serverPort_Spinner.addChangeListener(this);
    //    this.serverDebugPort_Spinner.addChangeListener(this);
    //    this.shutdownPort_Spinner.addChangeListener(this);

        projectNameTextField.getDocument().addDocumentListener(this);
        projectLocationTextField.getDocument().addDocumentListener(this);
        serverId_ComboBox.addActionListener(this);
        incremental_Deployment_CheckBox.addActionListener(this);

    }
    PortHandler portHandler;
    PortHandler debugPortHandler;
    PortHandler shutdownPortHandler;

    private void addPortListeners() {
        if (portHandler != null) {
            return;
        }
        JSpinner.NumberEditor me = (JSpinner.NumberEditor) serverPort_Spinner.getEditor();
        JFormattedTextField tf = me.getTextField();
        portHandler = new EmbServerPanelVisual.PortHandler(serverPort_Spinner);
        tf.getDocument().addDocumentListener(portHandler);

        me = (JSpinner.NumberEditor) serverDebugPort_Spinner.getEditor();
        tf = me.getTextField();
        debugPortHandler = new EmbServerPanelVisual.PortHandler(serverDebugPort_Spinner);
        tf.getDocument().addDocumentListener(debugPortHandler);

        //if (needsShutdownPort()) {
        me = (JSpinner.NumberEditor) shutdownPort_Spinner.getEditor();
        tf = me.getTextField();
        shutdownPortHandler = new EmbServerPanelVisual.PortHandler(serverDebugPort_Spinner);
        tf.getDocument().addDocumentListener(shutdownPortHandler);
        //}


    }

    public String getProjectName() {
        return this.projectNameTextField.getText();
    }

    public String getPortNumber() {
        return getPort(serverPort_Spinner);
    }

    public String getDebugPortNumber() {
        return getPort(serverDebugPort_Spinner);
    }

    public String getShutdownPortNumber() {
        return getPort(shutdownPort_Spinner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoManualButtonGroup = new javax.swing.ButtonGroup();
        projectNameLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        projectLocationLabel = new javax.swing.JLabel();
        projectLocationTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        createdFolderLabel = new javax.swing.JLabel();
        createdFolderTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        hostLabel = new javax.swing.JLabel();
        hostTextField = new javax.swing.JTextField();
        serverPortLabel = new javax.swing.JLabel();
        serverPort_Spinner = new javax.swing.JSpinner();
        serverDebugPortLabel = new javax.swing.JLabel();
        serverDebugPort_Spinner = new javax.swing.JSpinner();
        shutdownPort_Label = new javax.swing.JLabel();
        shutdownPort_Spinner = new javax.swing.JSpinner();
        incremental_Deployment_CheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        serverId_ComboBox = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(projectNameLabel, "Project Name:");

        projectLocationLabel.setLabelFor(projectLocationTextField);
        org.openide.awt.Mnemonics.setLocalizedText(projectLocationLabel, "Project Location:");

        org.openide.awt.Mnemonics.setLocalizedText(browseButton, "Browse...");
        browseButton.setActionCommand(org.openide.util.NbBundle.getMessage(EmbServerPanelVisual.class, "EmbServerPanelVisual.browseButton.actionCommand")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        createdFolderLabel.setLabelFor(createdFolderTextField);
        org.openide.awt.Mnemonics.setLocalizedText(createdFolderLabel, "Created Folder:");

        createdFolderTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(hostLabel, "Host:");

        hostTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(serverPortLabel, "Server Port:");

        serverPort_Spinner.setEditor(new javax.swing.JSpinner.NumberEditor(serverPort_Spinner, "#"));

        org.openide.awt.Mnemonics.setLocalizedText(serverDebugPortLabel, "Debug Port:");

        serverDebugPort_Spinner.setEditor(new javax.swing.JSpinner.NumberEditor(serverDebugPort_Spinner, "#"));

        org.openide.awt.Mnemonics.setLocalizedText(shutdownPort_Label, "Shutdown Port:"); // NOI18N

        shutdownPort_Spinner.setEditor(new javax.swing.JSpinner.NumberEditor(shutdownPort_Spinner, "#"));

        incremental_Deployment_CheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(incremental_Deployment_CheckBox, "Supports Incremental Deployment"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hostLabel)
                    .addComponent(serverPortLabel)
                    .addComponent(serverDebugPortLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shutdownPort_Label))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverPort_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(shutdownPort_Spinner, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serverDebugPort_Spinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(incremental_Deployment_CheckBox)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverPort_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverPortLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverDebugPort_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverDebugPortLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shutdownPort_Label)
                    .addComponent(shutdownPort_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(incremental_Deployment_CheckBox)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connection", jPanel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Server ID"); // NOI18N

        serverId_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(projectLocationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(projectNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createdFolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectNameTextField)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(createdFolderTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectLocationTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(21, 21, 21)
                                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serverId_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLocationLabel)
                    .addComponent(browseButton)
                    .addComponent(projectLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdFolderLabel)
                    .addComponent(createdFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(serverId_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        String command = evt.getActionCommand();
        if ("BROWSE".equals(command)) {
            JFileChooser chooser = new JFileChooser();
            FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
            chooser.setDialogTitle("Select Project Location");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            String path = this.projectLocationTextField.getText();
            if (path.length() > 0) {
                File f = new File(path);
                if (f.exists()) {
                    chooser.setSelectedFile(f);
                }
            }
            if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
                File projectDir = chooser.getSelectedFile();
                projectLocationTextField.setText(FileUtil.normalizeFile(projectDir).getAbsolutePath());
            }
            panel.fireChangeEvent();
        }

    }//GEN-LAST:event_browseButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup autoManualButtonGroup;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel createdFolderLabel;
    private javax.swing.JTextField createdFolderTextField;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JTextField hostTextField;
    private javax.swing.JCheckBox incremental_Deployment_CheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel projectLocationLabel;
    private javax.swing.JTextField projectLocationTextField;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JLabel serverDebugPortLabel;
    private javax.swing.JSpinner serverDebugPort_Spinner;
    private javax.swing.JComboBox serverId_ComboBox;
    private javax.swing.JLabel serverPortLabel;
    private javax.swing.JSpinner serverPort_Spinner;
    private javax.swing.JLabel shutdownPort_Label;
    private javax.swing.JSpinner shutdownPort_Spinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
        projectNameTextField.requestFocus();
    }

    boolean valid(WizardDescriptor wizardDescriptor) {
        wizardDescriptor.putProperty("WizardPanel_errorMessage", null);
        wizardDescriptor.putProperty("WizardPanel_warningMessage", null);

        if (projectNameTextField.getText().length() == 0) {
            // TODO if using org.openide.dialogs >= 7.8, can use WizardDescriptor.PROP_ERROR_MESSAGE:
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "Project Name is not a valid folder name.");
            return false; // Display name not specified
        }
        File f = FileUtil.normalizeFile(new File(projectLocationTextField.getText()).getAbsoluteFile());
        if (!f.isDirectory()) {
            String message = "Project Folder is not a valid path.";
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message);
            return false;
        }
        final File destFolder = FileUtil.normalizeFile(new File(createdFolderTextField.getText()).getAbsoluteFile());

        File projLoc = destFolder;
        while (projLoc != null && !projLoc.exists()) {
            projLoc = projLoc.getParentFile();
        }
        if (projLoc == null || !projLoc.canWrite()) {
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "Project Folder cannot be created.");
            return false;
        }

        if (FileUtil.toFileObject(projLoc) == null) {
            String message = "Project Folder is not a valid path.";
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message);
            return false;
        }

        File[] kids = destFolder.listFiles();
        if (destFolder.exists() && kids != null && kids.length > 0) {
            // Folder exists and is not empty
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "Project Folder already exists and is not empty.");
            return false;
        }

        int port;
        try {
            port = Integer.parseInt(getPort(serverPort_Spinner));
        } catch (NumberFormatException e) {
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_NOT_A_NUMBER", getPort(serverPort_Spinner)));
            return false;
        }
        if (port < 0) {
            // TODO if using org.openide.dialogs >= 7.8, can use WizardDescriptor.PROP_ERROR_MESSAGE:
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_INVALID_PORT"));
            return false;
        }
        
        try {
            Integer.parseInt(getPort(serverDebugPort_Spinner));
        } catch (NumberFormatException e) {
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_NOT_A_NUMBER", getPort(serverDebugPort_Spinner)));
            return false;
        }
        if (Integer.parseInt(getPort(serverDebugPort_Spinner)) < 0) {
            // TODO if using org.openide.dialogs >= 7.8, can use WizardDescriptor.PROP_ERROR_MESSAGE:
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_INVALID_DEBUG_PORT"));
            return false;
        }

        if (needsShutdownPort()) {
            try {
                Integer.parseInt(getPort(shutdownPort_Spinner));
            } catch (NumberFormatException e) {
                wizardDescriptor.putProperty("WizardPanel_errorMessage",
                        NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_NOT_A_NUMBER", getPort(shutdownPort_Spinner)));
                return false;
            }
            if (Integer.parseInt(getPort(shutdownPort_Spinner)) < 0) {
                // TODO if using org.openide.dialogs >= 7.8, can use WizardDescriptor.PROP_ERROR_MESSAGE:
                wizardDescriptor.putProperty("WizardPanel_errorMessage",
                        NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_INVALID_SHUTDOWN_PORT"));
                return false;
            }

        }
        port = Integer.parseInt(getPort(serverPort_Spinner));
        if (SuiteUtil.isHttpPortBusy_OLD(port, null)) {
            wizardDescriptor.putProperty("WizardPanel_warningMessage",
                    NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_HTTP_PORT_IN_USE", String.valueOf(port)));
            return true;
        }
        if (needsShutdownPort()) {
            port = Integer.parseInt(getPort(shutdownPort_Spinner));
            if (SuiteUtil.isShutdownPortBusy_OLD(port, null)) {
                wizardDescriptor.putProperty("WizardPanel_warningMessage",
                        NbBundle.getMessage(EmbServerCustomizerPanelVisual.class, "MSG_SHUTDOWN_PORT_IN_USE", String.valueOf(port)));
                return true;
            }
        }

        return true;
    }

    ServerSpecifics getSpecifics() {
        String serverId = BaseUtils.getServerIdByAcualId(getActualServerId());
        return BaseUtils.getServerSpecifics(serverId);
    }

    boolean needsShutdownPort() {
        return getSpecifics().needsShutdownPort();
    }

    void store(WizardDescriptor d) {
        String name = projectNameTextField.getText().trim();
        String folder = createdFolderTextField.getText().trim();

        d.putProperty("projdir", new File(folder));
        d.putProperty("name", name);

        d.putProperty(SuiteConstants.HTTP_PORT_PROP, getPort());
        d.putProperty(SuiteConstants.DEBUG_PORT_PROP, getDebugPort());
        d.putProperty(SuiteConstants.HOST_PROP, getHost());
//        String p = getShutdownPort();
        d.putProperty(SuiteConstants.SHUTDOWN_PORT_PROP, getShutdownPort());
        DefaultComboBoxModel<String> dcm = (DefaultComboBoxModel<String>) serverId_ComboBox.getModel();

        String actualServerId = (String) dcm.getSelectedItem();
        String serverId = BaseUtils.getServerIdByAcualId(actualServerId);
        d.putProperty(SuiteConstants.SERVER_ID_PROP, serverId);
        
        d.putProperty(SuiteConstants.SERVER_ACTUAL_ID_PROP, actualServerId);
        
        d.putProperty(SuiteConstants.INCREMENTAL_DEPLOYMENT, isIncrementalDeployment());
    }
    
    String isIncrementalDeployment() {
        return incremental_Deployment_CheckBox.isSelected() ?
                "true" : "false";
    }
    String getActualServerId() {
        DefaultComboBoxModel<String> dcm = (DefaultComboBoxModel<String>) serverId_ComboBox.getModel();
        return (String) dcm.getSelectedItem();
    }

    String getPort() {
        return String.valueOf(serverPort_Spinner.getValue());
    }

    String getPort(JSpinner spinner) {
        JSpinner.NumberEditor ne = (JSpinner.NumberEditor) spinner.getEditor();
        return ne.getTextField().getText();
    }

    String getDebugPort() {
        return String.valueOf(serverDebugPort_Spinner.getValue());
    }

    String getShutdownPort() {
        return String.valueOf(shutdownPort_Spinner.getValue());
    }

    String getHost() {
        return this.hostTextField.getText().trim();
    }

    DefaultListModel buildListModel(String[] strings) {
        DefaultListModel<String> m = new DefaultListModel<>();
        for (String s : strings) {
            m.addElement(s);
        }
        return m;
    }

    DefaultComboBoxModel<String> buildComboModel() {
        DefaultComboBoxModel<String> m = new DefaultComboBoxModel<>();
        
        DeploymentFactory[] fs = DeploymentFactoryManager.getInstance().getDeploymentFactories();
        
        for (DeploymentFactory f : fs) {
            if (!(f instanceof ServerSpecificsProvider)) {
                continue;
            }
            ServerSpecificsProvider ssp = (ServerSpecificsProvider) f;
            if ( ! (ssp.getSpecifics() instanceof EmbeddedServerSpecifics) ) {
                continue;
            }
            if ( ssp.getSpecifics() instanceof EmbeddedServerSpecifics ) {
                continue;
            }
            // OLD m.addElement(((ServerSpecificsProvider) f).getServerId());
            for ( String id : ((ServerSpecificsProvider) f).getSupportedServerIds()) {
                m.addElement(id);
            }
        }

        return m;
    }

    void read(WizardDescriptor settings) {
        wiz = settings;
        //-----  Server ID ---------
        DefaultComboBoxModel<String> dcm = buildComboModel();
        serverId_ComboBox.setModel(dcm);
        String actualServerId = (String) settings.getProperty(SuiteConstants.SERVER_ACTUAL_ID_PROP);
        if (actualServerId != null && dcm.getIndexOf(actualServerId) >= 0) {
            dcm.setSelectedItem(actualServerId);
        }

        File projectLocation = (File) settings.getProperty("projdir");
        if (projectLocation == null || projectLocation.getParentFile() == null || !projectLocation.getParentFile().isDirectory()) {
            projectLocation = ProjectChooser.getProjectsFolder();
        } else {
            projectLocation = projectLocation.getParentFile();
        }
        projectLocationTextField.setText(projectLocation.getAbsolutePath());

        String projectName = (String) settings.getProperty("name");
        if (projectName == null) {
            projectName = "EmbeddedServer";
        }
        String incrDepl = (String) settings.getProperty("incrementalDeployment");
        if ( incrDepl == null ) {
            incrDepl = "true";
        }
        if ( incrDepl.equals("true")) {
            incremental_Deployment_CheckBox.setSelected(true);
        } else {
            incremental_Deployment_CheckBox.setSelected(false);
        }
        
        projectNameTextField.setText(projectName);
        projectNameTextField.selectAll();
        hostTextField.setText("localhost");
        readDefaultPortSettings(settings);

    }

    void readDefaultPortSettings(WizardDescriptor settings) {
        
        String port = (String) settings.getProperty(SuiteConstants.HTTP_PORT_PROP);
        if (port == null) {
            port = String.valueOf(getSpecifics().getDefaultPort());
        }
        serverPort_Spinner.setValue(Integer.parseInt(port));

        port = (String) settings.getProperty(SuiteConstants.DEBUG_PORT_PROP);
        if (port == null) {
            port = String.valueOf(getSpecifics().getDefaultDebugPort());
        }
        serverDebugPort_Spinner.setValue(Integer.parseInt(port));

        port = (String) settings.getProperty(SuiteConstants.SHUTDOWN_PORT_PROP);

        if (port == null) {
            port = String.valueOf(getSpecifics().getDefaultShutdownPort());
        }

        shutdownPort_Spinner.setValue(Integer.parseInt(port));

        if (!needsShutdownPort()) {
            shutdownPort_Spinner.setVisible(false);
            shutdownPort_Label.setVisible(false);
        } else {
            shutdownPort_Spinner.setVisible(true);
            shutdownPort_Label.setVisible(true);
        }
        addPortListeners();
    }

    void validate(WizardDescriptor d) throws WizardValidationException {
        // nothing to validate
    }

    // Implementation of DocumentListener --------------------------------------
    @Override
    public void changedUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    /**
     * Handles changes in the Project name and project directory,
     */
    private void updateTexts(DocumentEvent e) {

        Document doc = e.getDocument();

        if (doc == projectNameTextField.getDocument() || doc == projectLocationTextField.getDocument()) {
            // Change in the project name
            String projectName = projectNameTextField.getText();
            String projectFolder = projectLocationTextField.getText();
            createdFolderTextField.setText(projectFolder + File.separatorChar + projectName);
        }
        panel.fireChangeEvent(); // Notify that the panel changed
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        panel.fireChangeEvent(); // Notify that the panel changed
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == serverId_ComboBox) {
            panel.fireChangeEvent();
            readDefaultPortSettings(wiz);
        } else if (e.getSource() == incremental_Deployment_CheckBox) {
            panel.fireChangeEvent();
            //readDefaultPortSettings(wiz);
        }

    }

    protected class PortHandler implements DocumentListener {

        private JSpinner spinner;

        public PortHandler(JSpinner spinner) {
            this.spinner = spinner;
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            firePropertyChange();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            firePropertyChange();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            firePropertyChange();
        }

        private void firePropertyChange() {
            JSpinner.NumberEditor me = (JSpinner.NumberEditor) spinner.getEditor();
            JFormattedTextField tf = me.getTextField();
            SwingUtilities.invokeLater(new Runnable(){

                @Override
                public void run() {
                    panel.fireChangeEvent();      
                }
            });
            //panel.fireChangeEvent();
            if (spinner == serverPort_Spinner) {
                EmbServerPanelVisual.this.firePropertyChange(PROP_PORT, null, tf.getText());
            } else if (spinner == shutdownPort_Spinner) {
                EmbServerPanelVisual.this.firePropertyChange(PROP_SHUTDOWN_PORT, null, tf.getText());
            } else if (spinner == serverDebugPort_Spinner) {
                EmbServerPanelVisual.this.firePropertyChange(PROP_DEBUG_PORT, null, tf.getText());
            }
            
        }
    }//class
}//class
